name: potionarmor
author: tWizT3d_dreaMr
version: 1.0.6
main: me.tWizT3d_dreaMr.PotionArmour.main
commands:
   Pareset:
      description: Reset players effects.
      usage: pareset <player>
   reload:
      description: Reloads config
      usage: reload
permissions:
  Potionarmor.pareset:
    default: op
    description: Allows the player to Pareset.
api-version: 1.18